name: DDPG Train
id: 84e10ba0-59cb-4580-bb9b-4f157334c2b7
category: Machine Learning\Train
description: Creates a DDPG for reinforcement learning and trains it
inputs:
- name: Environment name
  type: Mode
  default: 'Pendulum-v0'
  description: environment_name
  options:
    - 'Pendulum-v0'
    - 'BipedalWalker-v2'
- name: Learning rate
  type: Float
  default: 0.001
  description: learning_rate
- name: Max episodes
  type: Int
  default: 5000
  description: max_episodes
- name: Batch size
  type: Int
  default: 128
  description: batch_size
- name: Gamma
  type: Float
  defalut: 0.99
  description: gamma
outputs:
- name: Save path
  type: ModelFolder
  description: save_path
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: True
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.3
      - py-opencv=3.4.2
      - pip:
        - fire==0.1.3
        - gym==0.14.0
        - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
        - https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
        - git+https://github.com/zyh911/CustomModules.git@t-yuhazh/add_reinforcement_learning_ddpg#subdirectory=reinforcement-learning-ddpg
    command:
    - python
    - -m
    - ddpg.train
    args:
    - --environment_name
    - inputValue: Environment name
    - --learning_rate
    - inputValue: Learning rate
    - --max_episodes
    - inputValue: Max episodes
    - --batch_size
    - inputValue: Batch size
    - --gamma
    - inputValue: Gamma
    - --save_path
    - outputPath: Save path