name: Deeplabv3 Train
id: b9406d46-a5e9-4702-9faf-fe383607cc40
category: Machine Learning\Train
description: Creates a Deeplabv3 for semantic segmentation and trains it
inputs:
- name: Model type
  type: Mode
  default: 'deeplabv3_resnet101'
  description: model_type
  options:
    - 'deeplabv3_resnet101'
    - 'fcn_resnet101'
- name: Model path
  type: ModelFolder
  port: True
  description: model_path
- name: Data path
  type: GenericFolder
  port: True
  description: data_path
- name: Pretrained
  type: Boolean
  default: True
  description: pretrained
- name: Learning rate
  type: Float
  default: 0.0001
  description: learning_rate
- name: Epochs
  type: Int
  default: 10
  description: epochs
- name: Batch size
  type: Int
  default: 4
  description: batch_size
- name: Use CUDA
  type: Boolean
  default: False
  description: use_cuda
outputs:
- name: Save path
  type: ModelFolder
  description: save_path
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: True
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.3
      - py-opencv=3.4.2
      - pip:
        - fire==0.1.3
        - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
        - https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl
        - git+https://github.com/zyh911/CustomModules.git@t-yuhazh/add_semantic_segmentation_deeplabv3#subdirectory=semantic-segmentation-deeplabv3
    command:
    - python
    - -m
    - script.train
    args:
    - --model_type
    - inputValue: Model type
    - --model_path
    - inputValue: Model path
    - --data_path
    - inputValue: Data Path
    - --pretrained
    - inputValue: Pretrained
    - --learning_rate
    - inputValue: Learning rate
    - --epochs
    - inputValue: Epochs
    - --batch_size
    - inputValue: Batch size
    - --use_cuda
    - inputValue: Use CUDA
    - --save_path
    - outputPath: Save path
